Metrics/LineLength:
  Max: 200
  Exclude:
    - 'lib/iml.rb'
Metrics/BlockLength:
  Exclude: 
    - '*.gemspec'
    - '*.rake'
Style/ClassAndModuleChildren:
  Enabled: false
Documentation:
  Enabled: false
Rails: 
  Enabled: true
AllCops:
  Exclude:
    - 'spec/**/*'
